### ISSUE TITLE
register/login qui fonctionnent plus avec la route $route['(.*)'] = "none";

### ISSUE THREAD

**Issue by brissa-a** [awenig/datan#113]
Ya plein d'endroits dans le code ou au lieu de pointer vers le path ca pointe directement vers le controller/action. Ca fonctionnait bien jusqu'à qu'il y ait cette nouvelle route.

La bonne solution c'est de repasser partout pour qu'au lieu de faire appel au controller/action on fasse bien appel au path.

**Comment by brissa-a** [comment]
ex: https://github.com/awenig/datan/blob/master/application/views/users/register.php#L5

**Comment by remikel** [comment]
ah mince bien vu !
