### ISSUE TITLE
Ajouter newsletter

### ISSUE THREAD

**Issue by remikel** [awenig/datan#126]
Dans Suivez-nous, rajouter l'inscription à une newsletter.
Pas forcément en envoyer pour le moment, enfin je pensais 1 fois par mois pour résumer les posts twitter du mois par exemple.
Ca permettrait de "fidéliser" des users et préparer une liste de diffusion pour la sortie du questionnaire.

**Comment by awenig** [comment]
Check le` templates/footer.php` | lignes 10. J'avais mis cela dans l'idée de mettre une newsletter dans le passé.

**Comment by remikel** [comment]
Création de la table newsletter
Pop-in
Back ajout de l'e-mail
Back update/delete
Page gérer ses newsletter + se désabooner
protection multi-inscription newsletter
Service d'envoi de newsletter
Envoie de newsletter
