### ISSUE TITLE
Modification H1 page Département

### ISSUE THREAD

**Issue by GwennegM** [awenig/datan#135]
Sur les pages département modifier le H1 de la façon suivante : 

Exemple : 

https://datan.fr/deputes/ain-01 : 

"Ain (01)" -> "Député de l'Ain (01)"

**Comment by remikel** [comment]
le H1 sur les villes c'est pas le nom de la ville c'est : 
"Découvrez les députés élus dans la ville de Bourg-en-Bresse"
Il faut le changer ?

**Comment by GwennegM** [comment]
Oui j'avais maj le contenu du ticket mais pas le titre :/ on parle juste du H1 des pages Département :)
