### ISSUE TITLE
Bug d'une page normalement accessible au admin

### ISSUE THREAD

**Issue by Jeff-Le-Citoyen-Lambda** [awenig/datan#138]
Il me semble que cette page permet de voir facilement l'ensemble des votes de l'AN.

https://datan.fr/admin/votes_an/position

Elle ne fonctionne pas pour moi (sauf s'il s'agit d'une question de droit)
![image](https://user-images.githubusercontent.com/80222864/113202757-752d6f80-926b-11eb-91f5-ad0338bb12fb.png)

**Comment by awenig** [comment]
Merci @Jeff-Le-Citoyen-Lambda  c'est résolu :)
