### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by remikel** [awenig/datan#35]
/groupes/individual_votes_datan/larem
/groupes/larem/votes
Ces 2 pages sont les memes non ?

**Comment by awenig** [comment]
Oui ce sont les mêmes, la première URL c'est le nom de la fonction dans le controller, mais bizarre non c'est pas censé être geré dans le `routes` file ?

**Comment by awenig** [comment]
Donc, réponse SEO : en soit ce n'est pas grave comme on a pas de lien ver cette page ! Cependant ce serait le top si la page répond en 404. Tu penses que c'est possible ? Sinon, comme indiqué, pas catastrophique vu qu'on ne lie pas vers cette page.

**Comment by remikel** [comment]
Ok top, oui c'est faisable ! je vais regarder ça !
