### ISSUE TITLE
Code département

### ISSUE THREAD

**Issue by remikel** [awenig/datan#54]
Pourrait-on éviter d'avoir ça dans les requêtes simplement en mettant à jour la table circos ?
```
WHEN departement_code = "2b" THEN "02b"
WHEN departement_code = "2a" THEN "02a"
WHEN departement_code = "974" THEN "0ZD"
WHEN departement_code = "976" THEN "0ZM"
```
et en mettant directement 976 à la place de 0ZM par exemple ? J'ai pas l'impression que le code de département 0ZM par exemple soit utilisé d'une quelconque manière dans le code.

De même on pourrait aussi mettre la table insee à jour en renseignant le code département complet pour éviter ceci
```
WHEN d.departement_code = "973" THEN "97"
WHEN d.departement_code = "971" THEN "97"
WHEN d.departement_code = "986" THEN "98" 
```

Est-ce quelqu'un d'autres peut vérifier qu'il n'y ait pas d'impact ?

**Comment by awenig** [comment]
Yes ca pourrait être fait ; après le seul truc est que, si un jour on récupère un fichier open data circos ou dpt updaté, il faut se souvenir qu'on a changé le fichier d'origine, non ?

**Comment by remikel** [comment]
on aura qu'à garder le script qui modifie les colonnes quelques part comme ça on aura juste à le relancer au cas où

**Comment by awenig** [comment]
Yes, parfait. Je regarde demain soir les différentes écritures de ces départements dans toutes les bases, faire un "inventaire" et voir lesquelles ont modifie.
