### ISSUE TITLE
Obfuscation links page individual votes

### ISSUE THREAD

**Issue by awenig** [awenig/datan#59]
L'idée, pour les votes decryptés (https://datan.fr/votes/legislature-15/vote_3433), serait de crypter les liens dans la section "Pour mieux comprendre", comme les liens cryptés sur les pages députés. Le cryptage idéalement serait en place que pour les liens externes (autrement dit ceux qui ont attribut target="_blank"). 

Branche:  `feature/obfuscation-links-vote`. Cf le controller Votes.php, fonction créée: `text_url_obfuscation`, dans file `utility_helper.php` . Fonctionne que sur les votes decryptés, autrement dit ceux qui se trouvent mis en avant sur la home du site !

**Comment by remikel** [comment]
sur :
/votes/legislature-15/vote_2830
Le lien vers le député Patrick Hetzel sur le site datan.fr est obfusqué aussi.
(et aussi, le lien va sur datan.fr et pas sur mon localhost)

**Comment by brissa-a** [comment]
Ouaip parcequ'il est target="_blank" faudrait arriver a savoir si le href pointe vers datan ou pas ce qui est un peu plus compliqué

**Comment by remikel** [comment]
j'ai fait un commit si tu veux checké que ça pose pas de soucis

**Comment by brissa-a** [comment]
Effectivement ca fait le taf mais que pour les liens absolus. J'avais pas fait attention que c'était des liens absolu. Et du coup ca fait directement passer de localhost a la prod.

**Comment by awenig** [comment]
Alors, en soit, c'est parce que ce sont des anciens votes. Depuis un merge de ce matin, dès que tu écris un vote ou un post, avec la version 5 de ckeditor, soit c'est un lien qui pointe vers https://datan.fr et alors il a pas de target blank. Soit c'est un lien qui pointe vers extérieur et alors il y a un target blank. Qui dit target blank, dit automatiquement lien obfusqué. Donc ce problème est réglé pour les prochains votes.

**Comment by awenig** [comment]
De plus, pour la solution de Remi, cela fonctionne car on utilise **tout le temps** des liens absolus quand on écrit un vote dans le système.
