### ISSUE TITLE
Recadrage photos députés avec fond transparent

### ISSUE THREAD

**Issue by brissa-a** [awenig/datan#63]
![image](https://user-images.githubusercontent.com/2393492/110505739-b9ab6c80-80fe-11eb-97d4-079bd8cd1468.png)
Les députés ne peuvent pas être "dézoomé" car on verrait les bords de l'image.
Solution => utiliser les images avec un fond transparent puis utiliser un fond similaire

**Comment by brissa-a** [comment]
un apercu de ce que ca pourrait donner
![image](https://user-images.githubusercontent.com/2393492/110547152-d3b17300-812f-11eb-9027-1405bb503a0e.png)

**Comment by remikel** [comment]
Yes ça peut être pas mal, faut juste voir encore cette question de droit de "retouche" ^^

**Comment by awenig** [comment]
Yes j'aime bien, c'est beaucoup mieux, les députés ne sont pas tassés. Et si on veut changer le fond, à un moment, tester autre chose, c'est géré en CSS du coup ?

**Comment by brissa-a** [comment]
Le fond de damien abad ouaip CSS
`.card-depute .card-avatar {
 background: linear-gradient(#99BDDA, white);
}`

Pour les droits de retouche on devrait envoyer un mail a l'AN pour leur demander le droit d'utiliser les images. On en aurait le cœur net. Même si perso je pense que tant que on utilise ca de manière bienveillante on aura jamais de problème.
