### ISSUE TITLE
Enlever balise <a> dans les liens obfsuqués

### ISSUE THREAD

**Issue by awenig** [awenig/datan#71]
![image](https://user-images.githubusercontent.com/66798411/110819296-53edea80-828e-11eb-83b6-498584142386.png)

**Comment by brissa-a** [comment]
Ca permet de garder le style graphique des liens.

**Comment by awenig** [comment]
Deux SEO managers ont confirmé, il faut enlever. Je vais utiliser une classe qui existe déjà sur quelques liens, `underline`, pour l'adapter pour les liens obfusqués. Je m'en occupe.

**Comment by brissa-a** [comment]
![image](https://user-images.githubusercontent.com/2393492/112042293-a3ae9a80-8b47-11eb-8d31-e909271afc38.png)

Ya  certains lien en <a>  et d' autres en <span> dans cette section. Ya une raison a ca ?

**Comment by awenig** [comment]
Oui @brissa-a il y a une raison. Quand le site fait un link vers Datan sans no-follow, alors on fait un lien vers le site sans cryptage, c'est bien vu par google les "renvois d'ascenseurs", que deux sites s'auto-link.
